### ISSUE TITLE
invalid schema, expected mongodb

### ISSUE THREAD

**Issue by BlueRoboto** [winstonjs/winston-mongodb#102]
Hey there,
i see some people have un issues similar to mine.
I'm trying to configure basic winston logger with mongodb, but i get this error:
`winston-mongodb: error initialising logger Error: invalid schema, expected mongodb
    at module.exports (/home/vagrant/acigeo-plus/node_modules/mongodb/lib/url_parser.js:18:11)
    at connect (/home/vagrant/acigeo-plus/node_modules/mongodb/lib/mongo_client.js:480:16)
    at /home/vagrant/acigeo-plus/node_modules/mongodb/lib/mongo_client.js:234:7
    at Promise (<anonymous>)
    at Function.MongoClient.connect (/home/vagrant/acigeo-plus/node_modules/mongodb/lib/mongo_client.js:230:12)
    at connectToDatabase (/home/vagrant/acigeo-plus/node_modules/winston-mongodb/lib/winston-mongodb.js:139:32)
    at new exports.MongoDB (/home/vagrant/acigeo-plus/node_modules/winston-mongodb/lib/winston-mongodb.js:151:5)
    at Logger (/home/vagrant/acigeo-plus/server/boot/loggerWinston.js:68:9)
    at Object.module.exports [as func] (/home/vagrant/acigeo-plus/server/boot/loggerWinston.js:5:25)
    at /home/vagrant/acigeo-plus/node_modules/loopback-boot/lib/executor.js:315:9
    at iterate (/home/vagrant/acigeo-plus/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at /home/vagrant/acigeo-plus/node_modules/loopback-boot/node_modules/async/lib/async.js:157:25
    at /home/vagrant/acigeo-plus/node_modules/loopback-boot/lib/executor.js:317:7
    at iterate (/home/vagrant/acigeo-plus/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/home/vagrant/acigeo-plus/node_modules/loopback-boot/node_modules/async/lib/async.js:162:9)
    at runScripts (/home/vagrant/acigeo-plus/node_modules/loopback-boot/lib/executor.js:305:9)`

This is a part of my code in javascript:
`  function Logger(server, levelLog) {

    const Winston = require('winston'),
      DataSource = require('../datasources').db;

    require('winston-mongodb').MongoDB;

    if (!levelLog) {
      levelLog = 'info';
    }

    return new Winston.Logger({
      transports: [
        new Winston.transports.MongoDB({
          level: levelLog,
          collection: 'log',
          db: DataSource.database,
          host: DataSource.host,
          port: DataSource.port
        }),
        new Winston.transports.Console({
          level: 'debug',
          handleExceptions: true,
          json: false,
          colorize: true
        })
      ],
      exitOnError: false
    });
  }`

Thanks in advance.

**Comment by BlueRoboto** [comment]
+

**Comment by alisherafat** [comment]
same problem for me? 
any solution? 
should i only use db option for connection uri?

**Comment by yurijmikhalevich** [comment]
@BlueRoboto what is `DataSource.database`. Can you please provide a short runnable snippet which reproduces the problem?

**Comment by danialgifani** [comment]
Same problem : 

`var options = {
    
    db : "logs",
    "options" : {poolSize: 4, autoReconnect: true},
    host : process.env.MONGOLOG_HOST,
    port : process.env.MONGOLOG_PORT
    
}
var mongoLog = require('winston-mongodb').MongoDB;
// Set up the winston logger transports
winstonServer.logger = new (winston.Logger)({
   /* transports: [
        new winston.transports.File({ filename: '/var/log/winston/info.log' })
    ]*/
    transports: [
        new (winston.transports.Console)(),
        new (winston.transports.File)({
            name: 'error-file',
            filename: errorFileName,
            level: 'error',
            colorize: true,
            humanReadableUnhandledException: true,
            maxsize: '10000000',
            tailable: true,
            maxFiles: 50,
            zippedArchive: true
            
        }),
        new (winston.transports.File)({
            name: 'warn-file',
            filename: warnFileName,
            level: 'warn',
            colorize: true,
            humanReadableUnhandledException: true,
            maxsize: '10000000',
            tailable: true,
            maxFiles: 50,
            zippedArchive: true
        }),
        new (mongoLog)( options)
    ]
});`

**Comment by charlesponti** [comment]
This error is thrown when your `process.env.MONGOLOG_HOST` is not prefixed by `mongodb://`
