### ISSUE TITLE
MongoError: server instance pool was destroyed

### ISSUE THREAD

**Issue by bhumilsarvaiya** [winstonjs/winston-mongodb#125]
Hello,
After my mongodb server goes down for around like 2 mins, I start getting this error. Also after the mongodb server is up after this point, no logs are getting added to mongo collection.
```bash
MongoError: server instance pool was destroyed
    at Function.MongoError.create (/home/app/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at basicWriteValidations (/home/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:450:51)
    at Server.insert (/home/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:542:16)
    at Server.insert (/home/app/node_modules/mongodb/lib/server.js:390:17)
    at insertDocuments (/home/app/node_modules/mongodb/lib/collection.js:744:19)
    at insertOne (/home/app/node_modules/mongodb/lib/collection.js:439:3)
    at /home/app/node_modules/mongodb/lib/collection.js:431:5
    at new Promise (<anonymous>)
    at Collection.insertOne (/home/app/node_modules/mongodb/lib/collection.js:430:10)
    at process.nextTick (/home/app/node_modules/winston-mongodb/lib/winston-mongodb.js:217:44)
```
The way I am setting up mongodb with winston:
```js
require("winston-mongodb").MongoDB;
let logger = new winston.Logger({
    transports: [
        new winston.transports.MongoDB({
            db: `mongodb://${user}:${password}@${mongodb}:27017/${db}`,
            collection: "logs"
        })
    ]
});
```
I also tried with tryReconnect option but it didn't help.
Please let me know if I am doing it wrongly or do I need some workaround.
Thanks

**Comment by HugoPoi** [comment]
I have a similar issue with my setup
```
winston-mongodb: error initialising logger Error: connect ECONNREFUSED XXX.XXX.XXX.XXX:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}
```
I use a replicaset and when a member is down, winston doesn't connect, my other mongodb driver instance working as expected.
