### ISSUE TITLE
new mongodriver not compatible

### ISSUE THREAD

**Issue by WhiteTomX** [winstonjs/winston-mongodb#130]
Hey,

The following error is thrown if i use a string as db:

```
(node:20311) UnhandledPromiseRejectionWarning: TypeError: this.logDb.close is not a function
at exports.MongoDB.MongoDB.close (/path/npm/node_modules/winston-mongodb/lib/winston-mongodb.js:167:14)
at exports.MongoDB.TransportStream.once.src (/path/npm/node_modules/winston-transport/index.js:49:14)
at Object.onceWrapper (events.js:317:30)
at emitTwo (events.js:131:20)
at exports.MongoDB.emit (events.js:214:7)
at DerivedLogger.Readable.unpipe (/path/npm/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:733:8)
at unpipe (/path/npm/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:661:9)
at exports.MongoDB.onerror (/path/npm/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:638:5)
at emitOne (events.js:121:20)
at exports.MongoDB.emit (events.js:211:7)
at logDb.collection.insertOne.then.catch.err (/path/npm/node_modules/winston-mongodb/lib/winston-mongodb.js:207:12)
at /path/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

I think it is because the MongoDB has no .close() Method in V3.x anymore. So we have to save the client as another property or just the client. And referencing to client.db. I dont know which one is better.

best regards
WhiteTom

**Comment by nickvorie** [comment]
Having the same issue. Wondering what the fix is.

**Comment by rap2hpoutre** [comment]
See: #130
