### ISSUE TITLE
TypeError: db.close is not a function

### ISSUE THREAD

**Issue by GiordanoArman** [winstonjs/winston-mongodb#147]
Hi!

I think I have set up the transport properly, from time to time, when I boot the app and it gets set, it throws the following exception

```
2018-11-02T20:31:36.034231+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: db.close is not a function
2018-11-02T20:31:36.034259+00:00 app[web.1]:     at createCollection.then.err (/app/node_modules/winston-mongodb/lib/winston-mongodb.js:87:10)
2018-11-02T20:31:36.034261+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
2018-11-02T20:31:36.034406+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2018-11-02T20:31:36.034522+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gustavomassa** [comment]
I'm facing the same issue, it happens when you kill your mongodb server/instance while the app is running.

 ```
TypeError: this.logDb.close is not a function
6|wba      |     at exports.MongoDB.MongoDB.close (/home/wba/node_modules/winston-mongodb/lib/winston-mongodb.js:167:14)
6|wba      |     at exports.MongoDB.TransportStream.once.src (/home/wba/node_modules/winston-transport/index.js:49:14)
6|wba      |     at Object.onceWrapper (events.js:273:13)
6|wba      |     at exports.MongoDB.emit (events.js:187:15)
6|wba      |     at exports.MongoDB.EventEmitter.emit (domain.js:442:20)
6|wba      |     at DerivedLogger.Readable.unpipe (/home/wba/node_modules/readable-stream/lib/_stream_readable.js:733:8)
6|wba      |     at unpipe (/home/wba/node_modules/readable-stream/lib/_stream_readable.js:661:9)
6|wba      |     at exports.MongoDB.onerror (/home/wba/node_modules/readable-stream/lib/_stream_readable.js:638:5)
6|wba      |     at exports.MongoDB.emit (events.js:187:15)
6|wba      |     at exports.MongoDB.EventEmitter.emit (domain.js:442:20)
6|wba      |     at logDb.collection.insertOne.then.catch.err (/home/wba/node_modules/winston-mongodb/lib/winston-mongodb.js:207:12)
6|wba      |     at tryCatcher (/home/wba/node_modules/bluebird/js/release/util.js:16:23)
6|wba      |     at Promise._settlePromiseFromHandler (/home/wba/node_modules/bluebird/js/release/promise.js:512:31)
6|wba      |     at Promise._settlePromise (/home/wba/node_modules/bluebird/js/release/promise.js:569:18)
6|wba      |     at Promise._settlePromise0 (/home/wba/node_modules/bluebird/js/release/promise.js:614:10)
6|wba      |     at Promise._settlePromises (/home/wba/node_modules/bluebird/js/release/promise.js:690:18)
```

**Comment by mpatelatIBM** [comment]
any solution on how to resolve this?

**Comment by yurijmikhalevich** [comment]
Closed as duplicate to #130

**Comment by Elwilliko** [comment]
re-install mongodb and then  npm audit fix --force

**Comment by Cristian48** [comment]
tengo el mismo problema y no e podidoo solucionarlo
[1] error: WORKER unhandledRejection
[1] error: uncaughtException: db.close is not a function
[1] TypeError: db.close is not a function
[1]     at /app/node_modules/winston-mongodb/lib/winston-mongodb.js:87:10
[1]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
