### ISSUE TITLE
Initialization error:  MongoError: a collection already exists

### ISSUE THREAD

**Issue by misuti** [winstonjs/winston-mongodb#175]
I am using the following constructor
```js
new winston.transports.MongoDB({
    name: "http",
    db: process.env.MONGODB_URL,
    options: {
        poolSize: 2, useNewUrlParser: true,
        useUnifiedTopology: true
    },
    tryReconnect: true,
    collection: 'http',
    level: 'info'
})
```

It runs without issue for the first time, but whenever I run the code again, it gives me this error

```
winston-mongodb, initialization error:  MongoError: a collection 'database.http' already exists
    at MessageStream.messageHandler (/.../node_modules/mongodb/lib/cmap/connection.js:266:20)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/.../node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/.../node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.ondata (_stream_readable.js:714:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:304:12)
    at readableAddChunk (_stream_readable.js:280:9) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1596430109 },
  ok: 0,
  code: 48,
  codeName: 'NamespaceExists',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1596430109 },
    signature: { hash: [Binary], keyId: [Long] }
  }
}
```

**Comment by Swagtex** [comment]
@misuti 
My current "fix": ` npm install mongodb@3.3.3`

**Comment by a1300** [comment]
Thank you very much @Swagtex  :+1: 
This worked for me!

**Comment by BNHDev** [comment]
@Swagtex Thank you for your solution 👍👍👍

**Comment by keyyuki** [comment]
I have same issue and solution of @Swagtex not work for me T_T

**Comment by backflip** [comment]
This seems to be related to `Changes in behavior of Db.prototype.createCollection` in [mongodb@3.6.0](https://github.com/mongodb/node-mongodb-native/releases/tag/v3.6.0) (see [PR](https://github.com/mongodb/node-mongodb-native/pull/2278)). So everything before 3.6.0 should work.

**Comment by backflip** [comment]
Possible fix: https://github.com/winstonjs/winston-mongodb/pull/176

**Comment by ceopaludetto** [comment]
If you use various versions of mongodb in your codebase(such as mongoose), another solution is resolutions field in package.json, add:

```json
"resolutions": {
    "mongoose/**/mongodb": "3.3.3"
},
```

**Comment by BasitMaqsood** [comment]
> @misuti
> My current "fix": ` npm install mongodb@3.3.3`

Helpful, Thanks a lot
