### ISSUE TITLE
Load balancer mode requires driver version 4+

### ISSUE THREAD

**Issue by RubenatorX** [winstonjs/winston-mongodb#201]
So, due to a change in mongodb atlas server, I've had to upgrade the mongodb driver to 4.1+ (currently 4.1.4), but, when I try to use windston-mongodb after that update I get:
```
{
  level: 'trace',
  db: 'mongodb+srv://***/***?retryWrites=true&w=majority',
  collection: 'server_logs',
  options: { useNewUrlParser: true, useUnifiedTopology: true }
}
winston-mongodb: error initialising logger MongoParseError: Load balancer mode requires driver version 4+
    at QueryReqWrap.callback (***\project\node_modules\winston-mongodb\node_modules\mongodb\lib\core\uri_parser.js:111:27)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:212:10)
    at QueryReqWrap.callbackTrampoline (internal/async_hooks.js:130:17)
```
Does this package not support driver 4.1+? or do I just have something misconfigured?

**Comment by asdfdelta** [comment]
Did you ever solve this?

**Comment by RubenatorX** [comment]
> Did you ever solve this?

nope

**Comment by asdfdelta** [comment]
@RubenatorX I found the issue. The package is using Mongoose v5, it needs to upgrade to v6 in order to take advantage of the v4 driver from Mongodb.

I ended up copying the index.js and put it in a separate file at my root. Then installed the latest Mongoose and fastify-plugin, require('./newfilelocation.js') instead of the package and it seems to work great so far. A shame these guys don't maintain any of these packages.

**Comment by RubenatorX** [comment]
> @RubenatorX I found the issue. The package is using Mongoose v5, it needs to upgrade to v6 in order to take advantage of the v4 driver from Mongodb.
> 
> I ended up copying the index.js and put it in a separate file at my root. Then installed the latest Mongoose and fastify-plugin, require('./newfilelocation.js') instead of the package and it seems to work great so far. A shame these guys don't maintain any of these packages.
Ew. But ty haha. Not sure if I will try that or just handle error reporting/logging with something else

**Comment by asdfdelta** [comment]
@RubenatorX I thought briefly about making a 3rd package and trying to keep that up to date, but then https://xkcd.com/927/

If you take that plunge, let me know so I can import your package lol

**Comment by wbt** [comment]
>A shame these guys don't maintain any of these packages.

To be clear, there is zero funding to do so and as one of the most active maintainers these days, I don't currently use the Mongo driver so I don't have a lot of familiarity or incentive to dive into the tech and gain it.  https://xkcd.com/2347/ is a little more on the nose here...

**Comment by asdfdelta** [comment]
That's why we create issues to help you guys out. Just updating the package.json to use the v6 adapter of Mongoose will solve this issue.

**Comment by wbt** [comment]
>Just updating the package.json to use the v6 adapter of Mongoose will solve this issue.

Useful to know and the first time it's been said, but there's also backwards compatibility testing & verification that this doesn't break existing code.  That's hard for me specifically as I'm not currently a user of the mongoDB module.

**Comment by wbt** [comment]
The project is open to PRs and any submitted PRs are open to anyone testing and reviewing them to say what they found.

**Comment by DABH** [comment]
We updated to the latest version of mongoose on `master`, but we still need help upgrading to the latest `mongodb` package, see https://github.com/winstonjs/winston-mongodb/pull/223.  If anyone is willing to step up and volunteer to fix this, it would be a huge help and would likely solve this and several related issues on the project.

**Comment by klemensz** [comment]
> If anyone is willing to step up and volunteer to fix this

So you are saying that master is not working at the moment after upgrading to the latest version of mongoose? What's failing?

**Comment by DABH** [comment]
Yes
