### ISSUE TITLE
key with dots are not fully sanitized. only the first dot removed

### ISSUE THREAD

**Issue by Ijmir** [winstonjs/winston-mongodb#74]
```
/Users/john/Development/myProject/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

Error: key a[dot]b.c must not contain '.'
    at Error (native)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:731:19)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:596:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:754:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:596:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:754:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:754:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:754:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:754:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:754:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:754:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:596:17)
    at serializeObject (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:294:18)
    at serializeInto (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/serializer.js:754:17)
    at serialize (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/bson.js:49:27)
    at Query.toBin (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/lib/connection/commands.js:143:25)
    at executeWrite (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:69:20)
    at WireProtocol.insert (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:80:3)
    at Server.insert (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:502:35)
    at executeWriteOperation (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:896:37)
    at ReplSet.insert (/Users/john/Development/myProject/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:920:3)
    at ReplSet.insert (/Users/john/Development/myProject/node_modules/mongodb/lib/replset.js:371:18)
    at insertDocuments (/Users/john/Development/myProject/node_modules/mongodb/lib/collection.js:703:19)
    at insertOne (/Users/john/Development/myProject/node_modules/mongodb/lib/collection.js:409:3)
    at Collection.insertOne (/Users/john/Development/myProject/node_modules/mongodb/lib/collection.js:397:44)
    at /Users/john/Development/myProject/node_modules/winston-mongodb/lib/winston-mongodb.js:271:11
    at Db.collection (/Users/john/Development/myProject/node_modules/mongodb/lib/db.js:449:20)
    at /Users/john/Development/myProject/node_modules/winston-mongodb/lib/winston-mongodb.js:253:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback [as _tickCallback] (node.js:390:13)
```

**Comment by Ijmir** [comment]
#73
