### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by santanu-biswas** [winstonjs/winston-mongodb#86]
If there is an error while inserting log entry to MongoDB, Node.js gives the following warning:

```
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:69:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The problem occurs [here](https://github.com/winstonjs/winston-mongodb/blob/master/lib/winston-mongodb.js#L221) when [`this.emit('error', err)`](https://github.com/winstonjs/winston-mongodb/blob/master/lib/winston-mongodb.js#L221) gets called.

I am not sure if this warning is from _winston_ or from _winston-mongodb_.

**Comment by santanu-biswas** [comment]
On going through the code I figured out that since I did not define an error event listener for the mongodb transport, the error emitted from the catch block of the promise [here](https://github.com/winstonjs/winston-mongodb/blob/master/lib/winston-mongodb.js#L221) results in 'Unhandled promise rejection'.

The problem is resolved by defining error event listener:

`logger.transports.mongodb.on('error', err => console.log('Error saving log entry to MongoDB'));`
